# Generated by Django 4.1.5 on 2023-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('document', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=35)),
                ('last_names', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=40)),
                ('networks', models.CharField(max_length=250)),
            ],
        ),
    ]
