# Generated by Django 4.1.5 on 2023-02-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='document',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
