# Generated by Django 4.1.5 on 2023-02-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_about_me_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('shortname', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about_me',
            name='networks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.network'),
        ),
    ]
