# Generated by Django 4.1.5 on 2023-02-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_network_alter_about_me_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='shortname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
