# Generated by Django 4.1.5 on 2023-02-13 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_education', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('id_level_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.level_education')),
            ],
        ),
    ]
